- name: Create a user prometheus
  ansible.builtin.user:
    name: prometheus
    create_home: no
    shell: /bin/false
    system: true

- name: Download prometheus
  ansible.builtin.get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v2.45.0/prometheus-2.45.0.linux-amd64.tar.gz
    dest: /tmp/prometheus.tar.gz

- name: Extract prometheus tar file
  ansible.builtin.unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /tmp
    remote_src: yes

- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: "{{ item }}"
    owner: prometheus
    group: prometheus
    mode: '0755'
    state: directory
  loop:
    - /data
    - /etc/prometheus

- name: Copy files with owner and permissions
  ansible.builtin.copy:
    src: /tmp/prometheus-2.45.0.linux-amd64/{{ item }}
    dest: /usr/local/bin
    mode: '0755'
    remote_src: yes
  loop:
    - prometheus
    - promtool

- name: Copy prometheus files
  ansible.builtin.copy:
    src: /tmp/prometheus-2.45.0.linux-amd64/{{ item }}
    dest: /etc/prometheus
    remote_src: yes
  loop:
    - consoles
    - console_libraries
    - prometheus.yml

- name: Template a file
  ansible.builtin.template:
    src: prometheus/templates/prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service

- name: Start and enable prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: started
    enabled: yes
  retries: 2
  delay: 10
  register: result
  until: result is succeeded