- name: Install packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - software-properties-common
    state: present
    update_cache: yes

- name: Add an Apt signing key, uses whichever key is at the URL
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add Grafana repo
  ansible.builtin.apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    state: present

- name: Install Grafana
  ansible.builtin.apt:
    name: grafana
    state: present
    update_cache: yes

- name: Make sure a service unit is running
  ansible.builtin.systemd:
    state: started
    name: grafana-server
    enabled: yes